// <auto-generated />
using System;
using Synctool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Synctool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428074911_InitialMySqlCreate")]
    partial class InitialMySqlCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Synctool.Models.CostCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaingDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("CardMarkupPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CardPurchasePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PriceConversion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PricePPSource")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CostCalculations");
                });

            modelBuilder.Entity("Synctool.Models.KeaProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExcelFileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PromoCashPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x4")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x8")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UploadedFileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WholesalePrice120")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice30")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice60")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice90")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("KeaProducts");
                });

            modelBuilder.Entity("Synctool.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Synctool.Models.OlizCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampaignCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampaignEndDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampaignShortDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampaignStartDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DiscountNetAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastBarcodeScanDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastTransportDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UploadedFileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("OlizCampaigns");
                });

            modelBuilder.Entity("Synctool.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Synctool.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSessionId")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RememberMeToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Synctool.Models.WhiteGoodsProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnergyClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExcelFileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Installment2Down")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Installment2Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Installment4Down")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Installment4Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Installment8Down")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Installment8Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PromoCashPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x4")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromoInstall1x8")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UploadedFileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WholesalePrice120")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice30")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice60")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("WholesalePrice90")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("WhiteGoodsProducts");
                });

            modelBuilder.Entity("Synctool.Models.KeaProduct", b =>
                {
                    b.HasOne("Synctool.Models.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("Synctool.Models.Notification", b =>
                {
                    b.HasOne("Synctool.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synctool.Models.OlizCampaign", b =>
                {
                    b.HasOne("Synctool.Models.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("Synctool.Models.WhiteGoodsProduct", b =>
                {
                    b.HasOne("Synctool.Models.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });
#pragma warning restore 612, 618
        }
    }
}
